### ISSUE TITLE
something not working

### ISSUE THREAD

**Issue by jrhaberstroh** [ruipgil/changepy#1]
I tried forking this repo and adding a meanvar procedure, but it did not work. I went back and tried to produce an elbow plot for one of the other procedures (var), but that had an erratic shape. I think there is something wrong with the core of this program. It should be A/B tested against the R package to really figure out if it is functioning.

**Comment by ruipgil** [comment]
I’m going to take a closer look soon.

**Comment by ruipgil** [comment]
There was a bug in the main code that should be fixed.
I've also implemented the meanvar cost function.

Let me know if you still encounter the same issue, or if it's resolved.
